language: python
python:
- 3.8
- 3.9
before_install:
- pip install poetry
install:
- poetry install
script:
- poetry run black torcheck/ tests/
- poetry run flake8 torcheck/ tests/
- poetry run pytest --cov=torcheck/ tests/
before_deploy:
- poetry config pypi-token.pypi $PYPI_TOKEN
- poetry build
deploy:
  provider: script
  script: poetry publish
  skip_cleanup: true
  on:
    tags: true
