language: python
python:
- 3.7
- 3.8
- 3.9
before_install:
- pip install poetry
install:
- poetry install
script:
- poetry run black torcheck/ tests/
- poetry run flake8 torcheck/ tests/
- poetry run pytest --cov=torcheck/ tests/
before_deploy:
- poetry config pypi-token.pypi pypi-AgEIcHlwaS5vcmcCJDAwZjQyNTJkLTQ4MDMtNDU4OC04MGJjLThkMDQ2OGE3ZmM4OQACJXsicGVybWlzc2lvbnMiOiAidXNlciIsICJ2ZXJzaW9uIjogMX0AAAYgSry_Y_k5PprdXMUNLeg80JvAxy_VHWIwNu_IHryZPj4
- poetry build
deploy:
  provider: script
  script: poetry publish
  skip_cleanup: true
  on:
    tags: true
